server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native # Switch from Git to Native file system
  cloud:
    config:
      server:
        native:
          # Point explicitly to your config-data folder
          # 'classpath' works great if files are in src/main/resources, 
          # but for external folders, file:// is safer.
          search-locations: file:///${user.dir}/config-data

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/