# Global configurations shared by everyone
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  # Global Zipkin Config
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  
management:
  tracing:
    sampling:
      probability: 1.0